SpecialHq_Room1_MapScripts::
	.byte 0

SPECIAL_HQ__9_9_Script_008DEDE7::
	end

SPECIAL_HQ__9_9_Script_0097AD44::
	end

SPECIAL_HQ__9_9_Script_0097AD4F::
	end

SPECIAL_HQ__9_9_Script_0097AD59::
	end

SPECIAL_HQ__9_9_Script_0097AD64::
	end

SPECIAL_HQ__9_9_Script_0097B189::
	end

SPECIAL_HQ__9_9_Script_0097B270::
	end

SPECIAL_HQ__9_9_Script_0097B29C::
	end

SPECIAL_HQ__9_9_Script_0097B39B::
	end

SPECIAL_HQ__9_9_Script_0097B3FD::
	end

SPECIAL_HQ__9_9_Script_0097B477::
	end

SPECIAL_HQ__9_9_Script_0097B4DB::
	end

SPECIAL_HQ__9_9_Script_0097B51D::
	end

SPECIAL_HQ__9_9_Script_0097B570::
	end

SPECIAL_HQ__9_9_Script_0097B5BD::
	end

SPECIAL_HQ__9_9_Script_0097B61D::
	end

SPECIAL_HQ__9_9_Script_0097B6D8::
	end

SPECIAL_HQ__9_9_Script_0097B6E2::
	end

SPECIAL_HQ__9_9_Script_0097B6EC::
	end

SPECIAL_HQ__9_9_Script_0097C59D::
	end

SPECIAL_HQ__9_9_Script_0097CA9C::
	end

SPECIAL_HQ__9_9_Script_0097CB48::
	end

SPECIAL_HQ__9_9_Script_009CB65D::
	end

SPECIAL_HQ__9_9_Script_00A0AC4C::
	end

SPECIAL_HQ__9_9_Script_00A0AF62::
	end

SPECIAL_HQ__9_9_Script_00A0AF75::
	end
