FuchsiaCity_MapScripts::
	.byte 0

FuchsiaCity_EventScript_Dummy::
	end

FUCHSIA_CITY_3_7_Script_001BDF13::
	end

FUCHSIA_CITY_3_7_Script_008ED958::
	end

FUCHSIA_CITY_3_7_Script_00902AD1::
	end

FUCHSIA_CITY_3_7_Script_0090EC4F::
	end

FUCHSIA_CITY_3_7_Script_0090FFF4::
	end

FUCHSIA_CITY_3_7_Script_00912039::
	end

FUCHSIA_CITY_3_7_Script_0091217A::
	end

FUCHSIA_CITY_3_7_Script_00912542::
	end

FUCHSIA_CITY_3_7_Script_009128D1::
	end

FUCHSIA_CITY_3_7_Script_00936B49::
	end

FUCHSIA_CITY_3_7_Script_0093CCAC::
	end

FUCHSIA_CITY_3_7_Script_009E8318::
	end
