DragonsDen_Room9_MapScripts::
	.byte 0

DRAGON___S_DEN_1_84_Script_001BE00C::
	end

DRAGON___S_DEN_1_84_Script_001BEBF4::
	end

DRAGON___S_DEN_1_84_Script_001BEC01::
	end

DRAGON___S_DEN_1_84_Script_0084469A::
	end

DRAGON___S_DEN_1_84_Script_0084E707::
	end

DRAGON___S_DEN_1_84_Script_0084E77B::
	end

DRAGON___S_DEN_1_84_Script_0084E7D7::
	end

DRAGON___S_DEN_1_84_Script_0084EBD2::
	end

DRAGON___S_DEN_1_84_Script_0084FC8B::
	end

DRAGON___S_DEN_1_84_Script_009A4D54::
	end
