VioletCity_House1_MapScripts::
	.byte 0

@ TODO(LC): stub for unported LC script VIOLET_CITY_5_21_Script_00167C89
VIOLET_CITY_5_21_Script_00167C89::
	end

@ TODO(LC): stub for unported LC script VIOLET_CITY_5_21_Script_001718E0
VIOLET_CITY_5_21_Script_001718E0::
	end

@ TODO(LC): stub for unported LC script VIOLET_CITY_5_21_Script_001718F9
VIOLET_CITY_5_21_Script_001718F9::
	end

@ TODO(LC): preserved script content from replaced PetalburgCity_House1; disabled during LC map import
@ PetalburgCity_House1_MapScripts::
@ 	.byte 0
@
@ PetalburgCity_House1_EventScript_Man::
@ 	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
@ 	end
@
@ PetalburgCity_House1_EventScript_Woman::
@ 	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
@ 	end
@
@ PetalburgCity_House1_Text_TravelingIsWonderful:
@ 	.string "Traveling is wonderful!\p"
@ 	.string "When I was young, I roamed the seas\n"
@ 	.string "and the mountains!$"
@
@ PetalburgCity_House1_Text_GoOnAdventure:
@ 	.string "Sigh…\p"
@ 	.string "I wish I could go on an adventure\n"
@ 	.string "with some POKéMON…\p"
@ 	.string "Crawl through some damp grass…\n"
@ 	.string "Climb rocky, rugged mountains…\p"
@ 	.string "Cross the raging seas…\n"
@ 	.string "Wander about in dark caves…\p"
@ 	.string "And, sometimes, even get a little\n"
@ 	.string "homesick…\p"
@ 	.string "It must be fabulous to travel!$"
@
