MtMoon_Room1_MapScripts::
	.byte 0

MT__MOON_4_79_Script_0085BF11::
	end

MT__MOON_4_79_Script_009533AF::
	end

MT__MOON_4_79_Script_0097098E::
	end

MT__MOON_4_79_Script_00988671::
	end

MT__MOON_4_79_Script_009BA725::
	end

MT__MOON_4_79_Script_009C6416::
	end

MT__MOON_4_79_Script_009C647E::
	end

MT__MOON_4_79_Script_009C650A::
	end

MT__MOON_4_79_Script_009C6577::
	end

MT__MOON_4_79_Script_009C65F4::
	end

MT__MOON_4_79_Script_009C704D::
	end

MT__MOON_4_79_Script_009C7064::
	end
