DragonsDen_Room3_MapScripts::
	.byte 0

DRAGON___S_DEN_1_50_Script_001BE00C::
	end

DRAGON___S_DEN_1_50_Script_001BEA61::
	end

DRAGON___S_DEN_1_50_Script_00923D5E::
	end

DRAGON___S_DEN_1_50_Script_00923D6C::
	end

DRAGON___S_DEN_1_50_Script_009F6C90::
	end

DRAGON___S_DEN_1_50_Script_009F819F::
	end

DRAGON___S_DEN_1_50_Script_009F823A::
	end

DRAGON___S_DEN_1_50_Script_00A05195::
	end

DRAGON___S_DEN_1_50_Script_00A0522D::
	end

DRAGON___S_DEN_1_50_Script_00A052CD::
	end
