MtMoon_Room3_MapScripts::
	.byte 0

MT__MOON_5_67_Script_009533AF::
	end

MT__MOON_5_67_Script_0095F54B::
	end

MT__MOON_5_67_Script_00970525::
	end

MT__MOON_5_67_Script_00988326::
	end

MT__MOON_5_67_Script_0099EDB0::
	end

MT__MOON_5_67_Script_009C60F0::
	end

MT__MOON_5_67_Script_009C66C2::
	end

MT__MOON_5_67_Script_009C6748::
	end

MT__MOON_5_67_Script_009C67A9::
	end

MT__MOON_5_67_Script_009C6FF4::
	end
