LavenderTown_MapScripts::
	.byte 0

LavenderTown_EventScript_Dummy::
	end

LAVENDER_TOWN_3_4_Script_00917076::
	end

LAVENDER_TOWN_3_4_Script_00922C80::
	end

LAVENDER_TOWN_3_4_Script_00922CCF::
	end

LAVENDER_TOWN_3_4_Script_00922CFE::
	end

LAVENDER_TOWN_3_4_Script_00922D45::
	end

LAVENDER_TOWN_3_4_Script_0092330A::
	end

LAVENDER_TOWN_3_4_Script_0092AE05::
	end

LAVENDER_TOWN_3_4_Script_0092B00F::
	end

LAVENDER_TOWN_3_4_Script_0093000F::
	end

LAVENDER_TOWN_3_4_Script_00988773::
	end
