SilphCo_Room3_MapScripts::
	.byte 0

SILPH_CO__14_14_Script_00161660::
	end

SILPH_CO__14_14_Script_001A891B::
	end

SILPH_CO__14_14_Script_001A8935::
	end

SILPH_CO__14_14_Script_001BE873::
	end

SILPH_CO__14_14_Script_001BE880::
	end

SILPH_CO__14_14_Script_001BE88D::
	end

SILPH_CO__14_14_Script_001BE89A::
	end

SILPH_CO__14_14_Script_001BE8A7::
	end

SILPH_CO__14_14_Script_001BE8C1::
	end

SILPH_CO__14_14_Script_001BE8CE::
	end

SILPH_CO__14_14_Script_008DEEAB::
	end

SILPH_CO__14_14_Script_008DEF6D::
	end

SILPH_CO__14_14_Script_008DF032::
	end

SILPH_CO__14_14_Script_008DF0AE::
	end

SILPH_CO__14_14_Script_008DF15F::
	end

SILPH_CO__14_14_Script_008DF1CA::
	end

SILPH_CO__14_14_Script_008DF295::
	end

SILPH_CO__14_14_Script_008DF367::
	end

SILPH_CO__14_14_Script_008DF3C9::
	end

SILPH_CO__14_14_Script_008DF501::
	end

SILPH_CO__14_14_Script_008DFB04::
	end
