Route12_MapScripts::
	.byte 0

Route12_EventScript_Dummy::
	end

ROUTE_12_3_30_Script_001BDF13::
	end

ROUTE_12_3_30_Script_0091BE3C::
	end

ROUTE_12_3_30_Script_0091BFA7::
	end

ROUTE_12_3_30_Script_0091BFB5::
	end

ROUTE_12_3_30_Script_0091ED18::
	end

ROUTE_12_3_30_Script_0091EECF::
	end

ROUTE_12_3_30_Script_0091EFD1::
	end

ROUTE_12_3_30_Script_009201EB::
	end

ROUTE_12_3_30_Script_0092268B::
	end
