DragonsDen_Room7_MapScripts::
	.byte 0

DRAGON___S_DEN_1_74_Script_001BE00C::
	end

DRAGON___S_DEN_1_74_Script_001BEA95::
	end

DRAGON___S_DEN_1_74_Script_00843CF9::
	end

DRAGON___S_DEN_1_74_Script_00843DB8::
	end

DRAGON___S_DEN_1_74_Script_00843EFA::
	end

DRAGON___S_DEN_1_74_Script_00843FE3::
	end

DRAGON___S_DEN_1_74_Script_00844059::
	end

DRAGON___S_DEN_1_74_Script_00844132::
	end

DRAGON___S_DEN_1_74_Script_00844200::
	end

DRAGON___S_DEN_1_74_Script_00923D50::
	end
