VioletCity_House2_MapScripts::
	.byte 0

@ TODO(LC): stub for unported LC script VIOLET_CITY_5_20_Script_0016F602
VIOLET_CITY_5_20_Script_0016F602::
	end

@ TODO(LC): stub for unported LC script VIOLET_CITY_5_20_Script_0085DB8F
VIOLET_CITY_5_20_Script_0085DB8F::
	end

@ TODO(LC): preserved script content from replaced PetalburgCity_House2; disabled during LC map import
@ PetalburgCity_House2_MapScripts::
@ 	.byte 0
@
@ PetalburgCity_House2_EventScript_Woman::
@ 	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
@ 	end
@
@ PetalburgCity_House2_EventScript_SchoolKid::
@ 	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
@ 	end
@
@ PetalburgCity_House2_Text_NormanBecameGymLeader:
@ 	.string "NORMAN became our town's new\n"
@ 	.string "GYM LEADER.\p"
@ 	.string "I think he called his family over from\n"
@ 	.string "somewhere far away.$"
@
@ PetalburgCity_House2_Text_BattledNormanOnce:
@ 	.string "I battled NORMAN once, but, whew,\n"
@ 	.string "he was way too strong.\p"
@ 	.string "How would I put it?\p"
@ 	.string "I just got the feeling that he\n"
@ 	.string "lives for POKéMON.$"
@
