DragonsDen_Room10_MapScripts::
	.byte 0

DRAGON___S_DEN_1_85_Script_001BE00C::
	end

DRAGON___S_DEN_1_85_Script_001BE6D3::
	end

DRAGON___S_DEN_1_85_Script_001BEC0E::
	end

DRAGON___S_DEN_1_85_Script_001BED46::
	end

DRAGON___S_DEN_1_85_Script_0084446A::
	end

DRAGON___S_DEN_1_85_Script_00844515::
	end

DRAGON___S_DEN_1_85_Script_008445C7::
	end

DRAGON___S_DEN_1_85_Script_00844753::
	end

DRAGON___S_DEN_1_85_Script_0084E4EA::
	end

DRAGON___S_DEN_1_85_Script_0084E69D::
	end

DRAGON___S_DEN_1_85_Script_0084E842::
	end

DRAGON___S_DEN_1_85_Script_0084E95D::
	end

DRAGON___S_DEN_1_85_Script_0084EB09::
	end

DRAGON___S_DEN_1_85_Script_00974503::
	end
