SilphCo_Room4_MapScripts::
	.byte 0

SILPH_CO__14_15_Script_00161660::
	end

SILPH_CO__14_15_Script_00161669::
	end

SILPH_CO__14_15_Script_00161680::
	end

SILPH_CO__14_15_Script_001616AE::
	end

SILPH_CO__14_15_Script_001A891B::
	end

SILPH_CO__14_15_Script_001A8935::
	end

SILPH_CO__14_15_Script_001BE8DB::
	end

SILPH_CO__14_15_Script_001BE8E8::
	end

SILPH_CO__14_15_Script_001BE8F5::
	end

SILPH_CO__14_15_Script_001BE902::
	end

SILPH_CO__14_15_Script_001BE90F::
	end

SILPH_CO__14_15_Script_001BEB4B::
	end

SILPH_CO__14_15_Script_00879E3E::
	end

SILPH_CO__14_15_Script_008DF48F::
	end

SILPH_CO__14_15_Script_008DF5CA::
	end

SILPH_CO__14_15_Script_008DF757::
	end

SILPH_CO__14_15_Script_008DF826::
	end

SILPH_CO__14_15_Script_008DF83E::
	end

SILPH_CO__14_15_Script_008DF9AB::
	end

SILPH_CO__14_15_Script_008DFB76::
	end

SILPH_CO__14_15_Script_008E1C62::
	end
