SSAqua_Room2_MapScripts::
	.byte 0

S_S__AQUA_1_6_Script_008DA249::
	end

S_S__AQUA_1_6_Script_008DA4C5::
	end

S_S__AQUA_1_6_Script_008DA5DC::
	end

S_S__AQUA_1_6_Script_008DA66C::
	end

S_S__AQUA_1_6_Script_00911B21::
	end

S_S__AQUA_1_6_Script_00912021::
	end

S_S__AQUA_1_6_Script_009120E5::
	end

S_S__AQUA_1_6_Script_00912A60::
	end

S_S__AQUA_1_6_Script_00912B0F::
	end

S_S__AQUA_1_6_Script_00912BA8::
	end

S_S__AQUA_1_6_Script_00913014::
	end
