DragonsDen_Room5_MapScripts::
	.byte 0

DRAGON___S_DEN_1_72_Script_001BE00C::
	end

DRAGON___S_DEN_1_72_Script_001BE11D::
	end

DRAGON___S_DEN_1_72_Script_001BEA47::
	end

DRAGON___S_DEN_1_72_Script_001BEA54::
	end

DRAGON___S_DEN_1_72_Script_0084EF04::
	end

DRAGON___S_DEN_1_72_Script_0084EF69::
	end

DRAGON___S_DEN_1_72_Script_0084EF78::
	end

DRAGON___S_DEN_1_72_Script_0084EF87::
	end

DRAGON___S_DEN_1_72_Script_0084EF96::
	end

DRAGON___S_DEN_1_72_Script_00850B1F::
	end

DRAGON___S_DEN_1_72_Script_00850BC6::
	end

DRAGON___S_DEN_1_72_Script_00850CA5::
	end

DRAGON___S_DEN_1_72_Script_00868E0F::
	end

DRAGON___S_DEN_1_72_Script_00868EA3::
	end

DRAGON___S_DEN_1_72_Script_0090A2F5::
	end

DRAGON___S_DEN_1_72_Script_00921BD4::
	end

DRAGON___S_DEN_1_72_Script_009DA029::
	end

DRAGON___S_DEN_1_72_Script_009F2641::
	end

DRAGON___S_DEN_1_72_Script_00A71C0C::
	end
