GoldenrodCity_DepartmentStore_Room9_MapScripts::
	.byte 0

GOLDENROD_DEPT__2_96_Script_001BE5CF::
	end

GOLDENROD_DEPT__2_96_Script_001BE5DC::
	end

GOLDENROD_DEPT__2_96_Script_001BE5E9::
	end

GOLDENROD_DEPT__2_96_Script_001BE5F6::
	end

GOLDENROD_DEPT__2_96_Script_0085E0BD::
	end

GOLDENROD_DEPT__2_96_Script_0085E0E1::
	end

GOLDENROD_DEPT__2_96_Script_00860C85::
	end

GOLDENROD_DEPT__2_96_Script_00860CD7::
	end
