DragonsDen_Room6_MapScripts::
	.byte 0

DRAGON___S_DEN_1_73_Script_001BE00C::
	end

DRAGON___S_DEN_1_73_Script_001BEA61::
	end

DRAGON___S_DEN_1_73_Script_00841D71::
	end

DRAGON___S_DEN_1_73_Script_00841F0F::
	end

DRAGON___S_DEN_1_73_Script_00843A91::
	end

DRAGON___S_DEN_1_73_Script_00843B40::
	end

DRAGON___S_DEN_1_73_Script_00843C11::
	end

DRAGON___S_DEN_1_73_Script_00923D5E::
	end

DRAGON___S_DEN_1_73_Script_00923D6C::
	end
