DragonsDen_Room1_MapScripts::
	.byte 0

DRAGON___S_DEN_1_48_Script_001BE00C::
	end

DRAGON___S_DEN_1_48_Script_001BE11D::
	end

DRAGON___S_DEN_1_48_Script_0084EF69::
	end

DRAGON___S_DEN_1_48_Script_0090A2F5::
	end

DRAGON___S_DEN_1_48_Script_009E474F::
	end

DRAGON___S_DEN_1_48_Script_009E8250::
	end

DRAGON___S_DEN_1_48_Script_009E8350::
	end

DRAGON___S_DEN_1_48_Script_009E8434::
	end

DRAGON___S_DEN_1_48_Script_009EBFB8::
	end

DRAGON___S_DEN_1_48_Script_009EEB67::
	end

DRAGON___S_DEN_1_48_Script_009F2641::
	end

DRAGON___S_DEN_1_48_Script_009F275D::
	end

DRAGON___S_DEN_1_48_Script_009F59A2::
	end

DRAGON___S_DEN_1_48_Script_009F59B7::
	end

DRAGON___S_DEN_1_48_Script_009F59CC::
	end

DRAGON___S_DEN_1_48_Script_009F5A74::
	end

DRAGON___S_DEN_1_48_Script_009F5B12::
	end

DRAGON___S_DEN_1_48_Script_009F5BE6::
	end

DRAGON___S_DEN_1_48_Script_009F5CA0::
	end

DRAGON___S_DEN_1_48_Script_009F7AC8::
	end

DRAGON___S_DEN_1_48_Script_00A08A14::
	end
