Route9_MapScripts::
	.byte 0

Route9_EventScript_Dummy::
	end

ROUTE_9_3_27_Script_00167FD0::
	end

ROUTE_9_3_27_Script_001A9EAF::
	end

ROUTE_9_3_27_Script_001BDF13::
	end

ROUTE_9_3_27_Script_001BE6B9::
	end

ROUTE_9_3_27_Script_001BEAFD::
	end

ROUTE_9_3_27_Script_0092C0B1::
	end

ROUTE_9_3_27_Script_0092C0BF::
	end

ROUTE_9_3_27_Script_0093FFF2::
	end

ROUTE_9_3_27_Script_00944481::
	end

ROUTE_9_3_27_Script_00944855::
	end

ROUTE_9_3_27_Script_00944909::
	end

ROUTE_9_3_27_Script_009449EB::
	end

ROUTE_9_3_27_Script_00944AA0::
	end

ROUTE_9_3_27_Script_00944B72::
	end
