SproutTower_2F_MapScripts::
	.byte 0

@ TODO(LC): stub for unported LC script SPROUT_TOWER_2_12_Script_0016779B
SPROUT_TOWER_2_12_Script_0016779B::
	end

@ TODO(LC): stub for unported LC script SPROUT_TOWER_2_12_Script_00805577
SPROUT_TOWER_2_12_Script_00805577::
	end

@ TODO(LC): stub for unported LC script SPROUT_TOWER_2_12_Script_0080561C
SPROUT_TOWER_2_12_Script_0080561C::
	end

@ TODO(LC): stub for unported LC script SPROUT_TOWER_2_12_Script_00805839
SPROUT_TOWER_2_12_Script_00805839::
	end

@ TODO(LC): preserved script content from replaced Underwater_SootopolisCity; disabled during LC map import
@ Underwater_SootopolisCity_MapScripts::
@ 	map_script MAP_SCRIPT_ON_RESUME, Underwater_SootopolisCity_OnResume
@ 	.byte 0
@
@ Underwater_SootopolisCity_OnResume:
@ 	setdivewarp MAP_CELADON_CITY, 29, 53
@ 	end
@
