NewBarkTown_House1_MapScripts::
	.byte 0

NewBarkTown_House1_EventScript_AspiringResearcher::
    msgbox NewBarkTown_House1_Text_AspiringResearcher, MSGBOX_NPC
    end

NewBarkTown_House1_EventScript_AssistantMother::
    msgbox NewBarkTown_House1_Text_AssistantMother, MSGBOX_NPC
    end

NewBarkTown_House1_Text_AspiringResearcher:
    .string "PIKACHU is an evolved POKéMON.\n"
    .string "I was amazed by PROF. ELM's findings.\p"
    .string "He's so famous for his research on\n"
    .string "POKéMON evolution.\p"
    .string "...sigh...\p"
    .string "I wish I could be a researcher like\n"
    .string "him...$"

NewBarkTown_House1_Text_AssistantMother:
    .string "My daughter is adamant about\n"
    .string "becoming PROF. ELM's assistant.\p"
    .string "She really loves POKéMON!\n"
    .string "But then, so do I!$"
