SilphCo_Room2_MapScripts::
	.byte 0

SILPH_CO__14_13_Script_00161680::
	end

SILPH_CO__14_13_Script_001A8935::
	end

SILPH_CO__14_13_Script_001BE866::
	end

SILPH_CO__14_13_Script_001BEE09::
	end

SILPH_CO__14_13_Script_008DEA95::
	end

SILPH_CO__14_13_Script_008DEB97::
	end

SILPH_CO__14_13_Script_008DEC34::
	end

SILPH_CO__14_13_Script_008DECF3::
	end

SILPH_CO__14_13_Script_008DEDE7::
	end

SILPH_CO__14_13_Script_008DFA92::
	end
