DragonsDen_Room2_MapScripts::
	.byte 0

DRAGON___S_DEN_1_49_Script_001BE00C::
	end

DRAGON___S_DEN_1_49_Script_001BE11D::
	end

DRAGON___S_DEN_1_49_Script_0084EF69::
	end

DRAGON___S_DEN_1_49_Script_0090A2F5::
	end

DRAGON___S_DEN_1_49_Script_00921BD4::
	end

DRAGON___S_DEN_1_49_Script_009E8350::
	end

DRAGON___S_DEN_1_49_Script_009EEB67::
	end

DRAGON___S_DEN_1_49_Script_009F00E7::
	end

DRAGON___S_DEN_1_49_Script_009F2641::
	end

DRAGON___S_DEN_1_49_Script_009F275D::
	end

DRAGON___S_DEN_1_49_Script_009F59A2::
	end

DRAGON___S_DEN_1_49_Script_009F59B7::
	end

DRAGON___S_DEN_1_49_Script_009F6DDD::
	end

DRAGON___S_DEN_1_49_Script_009F7AF7::
	end

DRAGON___S_DEN_1_49_Script_009F7E71::
	end

DRAGON___S_DEN_1_49_Script_009F7F01::
	end

DRAGON___S_DEN_1_49_Script_009F7F19::
	end

DRAGON___S_DEN_1_49_Script_009F805C::
	end

DRAGON___S_DEN_1_49_Script_009F80E0::
	end

DRAGON___S_DEN_1_49_Script_009F8192::
	end

DRAGON___S_DEN_1_49_Script_00A0895C::
	end
