LeafBayCity_DepartmentStore_Room2_MapScripts::
	.byte 0

LEAF_BAY_DEPT__2_22_Script_0016C034::
	end

LEAF_BAY_DEPT__2_22_Script_00969DF8::
	end

LEAF_BAY_DEPT__2_22_Script_00969EF7::
	end

LEAF_BAY_DEPT__2_22_Script_0096A476::
	end

LEAF_BAY_DEPT__2_22_Script_0096A482::
	end

LEAF_BAY_DEPT__2_22_Script_0096A48E::
	end

LEAF_BAY_DEPT__2_22_Script_0096A52B::
	end

LEAF_BAY_DEPT__2_22_Script_0096A92B::
	end
