PewterCity_PokemonCenter_MapScripts::
	.byte 0

PEWTER_CITY_5_33_Script_00171619::
	end

PEWTER_CITY_5_33_Script_00171D00::
	end

PEWTER_CITY_5_33_Script_0092BFBA::
	end

PEWTER_CITY_5_33_Script_00936B5C::
	end

PEWTER_CITY_5_33_Script_00936BC9::
	end

PEWTER_CITY_5_33_Script_009519BA::
	end

PEWTER_CITY_5_33_Script_009519CE::
	end

PEWTER_CITY_5_33_Script_00951A16::
	end

PEWTER_CITY_5_33_Script_0098BDC8::
	end
