CeladonCity_DepartmentStore_Room3_MapScripts::
	.byte 0

CELADON_DEPT__10_2_Script_0016BBAF::
	end

CELADON_DEPT__10_2_Script_0016BBB8::
	end

CELADON_DEPT__10_2_Script_0016BBC1::
	end

CELADON_DEPT__10_2_Script_0016BBCA::
	end

CELADON_DEPT__10_2_Script_0016BBD3::
	end

CELADON_DEPT__10_2_Script_0016BBE5::
	end

CELADON_DEPT__10_2_Script_008E4F8E::
	end

CELADON_DEPT__10_2_Script_008E4FC4::
	end

CELADON_DEPT__10_2_Script_008E4FF5::
	end

CELADON_DEPT__10_2_Script_008E503B::
	end

CELADON_DEPT__10_2_Script_008E508A::
	end

CELADON_DEPT__10_2_Script_008E5A6C::
	end
