Route2_MapScripts::
	.byte 0

Route2_EventScript_Dummy::
	end

ROUTE_2_3_20_Script_001BDF13::
	end

ROUTE_2_3_20_Script_00943584::
	end

ROUTE_2_3_20_Script_0094B380::
	end

ROUTE_2_3_20_Script_0094B397::
	end

ROUTE_2_3_20_Script_0094FFE6::
	end

ROUTE_2_3_20_Script_009502E5::
	end

ROUTE_2_3_20_Script_00950392::
	end

ROUTE_2_3_20_Script_009503D1::
	end

ROUTE_2_3_20_Script_009503DE::
	end

ROUTE_2_3_20_Script_00950EE9::
	end

ROUTE_2_3_20_Script_0097509D::
	end

Kecleon_Text_SomethingUnseeable::
	.string "There's something here\nthat can't be seen!$"

Kecleon_Text_WantToUseDevonScope::
	.string "Use DEVON SCOPE?$"

Kecleon_Text_UseDevonScopeMonAttacked::
	.string "The KECLEON attacked!$"
