CeladonCity_MapScripts::
	.byte 0

CeladonCity_EventScript_Dummy::
	end

EventScript_ClosedSootopolisDoor::
	end

CELADON_CITY_3_6_Script_00166CC5::
	end

CELADON_CITY_3_6_Script_00166CDC::
	end

CELADON_CITY_3_6_Script_00166D27::
	end

CELADON_CITY_3_6_Script_00166D30::
	end

CELADON_CITY_3_6_Script_00166D48::
	end

CELADON_CITY_3_6_Script_00166D51::
	end

CELADON_CITY_3_6_Script_001BDF13::
	end

CELADON_CITY_3_6_Script_008D5733::
	end

CELADON_CITY_3_6_Script_008DA200::
	end

CELADON_CITY_3_6_Script_008DFCFF::
	end

CELADON_CITY_3_6_Script_008E1F01::
	end

CELADON_CITY_3_6_Script_008E29FB::
	end

CELADON_CITY_3_6_Script_008E2E16::
	end

CELADON_CITY_3_6_Script_008E3C67::
	end

CELADON_CITY_3_6_Script_008E47F1::
	end

CELADON_CITY_3_6_Script_008E4837::
	end
